/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.breno.jogodaforca.view;

import br.com.breno.jogodaforca.service.MusicPlayerService;
import javax.swing.ButtonGroup;

/**
 *
 * @author breno
 */
public class ConfigPanel extends javax.swing.JPanel {
    
    private MainFrame mainFrame;
    private MusicPlayerService player;

    /**
     * Creates new form ConfigPanel
     */
    public ConfigPanel() {
        initComponents();
        
        this.player = MusicPlayerService.getInstance();
        
        agruparBotoesTela();
        configurarListeners();
        configurarSliderVolume();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTituloConfig = new javax.swing.JLabel();
        panelTela = new javax.swing.JPanel();
        radioJanela = new javax.swing.JRadioButton();
        radioSemBorda = new javax.swing.JRadioButton();
        radioTelaCheia = new javax.swing.JRadioButton();
        panelSom = new javax.swing.JPanel();
        sliderVolumeMaster = new javax.swing.JSlider();
        btnVoltarConfig = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 0));
        setForeground(new java.awt.Color(0, 51, 0));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        setLayout(layout);

        lblTituloConfig.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        lblTituloConfig.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloConfig.setText("Configurações");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(lblTituloConfig, gridBagConstraints);

        panelTela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modo de Tela", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelTela.setOpaque(false);
        panelTela.setLayout(new java.awt.GridLayout(1, 3, 2, 0));

        radioJanela.setForeground(new java.awt.Color(255, 255, 255));
        radioJanela.setText("Janela (Padrão)");
        panelTela.add(radioJanela);

        radioSemBorda.setForeground(new java.awt.Color(255, 255, 255));
        radioSemBorda.setText("Janela Sem Borda");
        panelTela.add(radioSemBorda);

        radioTelaCheia.setForeground(new java.awt.Color(255, 255, 255));
        radioTelaCheia.setText("Tela Cheia");
        panelTela.add(radioTelaCheia);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(panelTela, gridBagConstraints);

        panelSom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Volume da Música", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelSom.setOpaque(false);
        panelSom.setPreferredSize(new java.awt.Dimension(350, 70));
        panelSom.setLayout(new java.awt.BorderLayout());
        panelSom.add(sliderVolumeMaster, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        add(panelSom, gridBagConstraints);

        btnVoltarConfig.setText("Voltar ao Menu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        add(btnVoltarConfig, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

        private void agruparBotoesTela(){
        ButtonGroup groupTela = new ButtonGroup();
        groupTela.add(radioJanela);
        groupTela.add(radioSemBorda);
        groupTela.add(radioTelaCheia);
        
        radioJanela.setSelected(true);
            
        }
        
        private void configurarSliderVolume() {
        sliderVolumeMaster.setValue(100); 
    }
        
        private void configurarListeners() {
        this.addHierarchyListener(e -> {
            if (e.getChangeFlags() == java.awt.event.HierarchyEvent.PARENT_CHANGED &&
                javax.swing.SwingUtilities.getWindowAncestor(this) != null) {
                
                mainFrame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            }
        });

        btnVoltarConfig.addActionListener(e -> {
            if (mainFrame != null) {
                mainFrame.mostrarTela("MENU");
                mainFrame.pack(); // Volta ao tamanho do Menu
                mainFrame.setLocationRelativeTo(null);
            }
        });
        
        radioJanela.addActionListener(e -> {
            if (mainFrame != null) mainFrame.setModoTela(0);
        });
        radioSemBorda.addActionListener(e -> {
            if (mainFrame != null) mainFrame.setModoTela(1);
        });
        radioTelaCheia.addActionListener(e -> {
            if (mainFrame != null) mainFrame.setModoTela(2);
        });
        
        sliderVolumeMaster.addChangeListener(e -> {
            if (player != null) {
                double volume = sliderVolumeMaster.getValue() / 100.0;
                player.setVolume(volume);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarConfig;
    private javax.swing.JLabel lblTituloConfig;
    private javax.swing.JPanel panelSom;
    private javax.swing.JPanel panelTela;
    private javax.swing.JRadioButton radioJanela;
    private javax.swing.JRadioButton radioSemBorda;
    private javax.swing.JRadioButton radioTelaCheia;
    private javax.swing.JSlider sliderVolumeMaster;
    // End of variables declaration//GEN-END:variables
}
