/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.breno.jogodaforca.view;

import br.com.breno.jogodaforca.dao.MongoConnection;
import br.com.breno.jogodaforca.service.MusicPlayerService;
import javax.swing.JOptionPane;

/**
 *
 * @author breno
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private MenuPanel menuPanel;
    private GamePanel gamePanel;
    private RankingPanel rankingPanel;
    private ConfigPanel configPanel;
    private SelecaoPanel selecaoPanel;

    public MainFrame() {
        initComponents();
        //icone
        try {
            java.net.URL iconeURL = getClass().getResource("/images/icone.png");

            if (iconeURL != null) {
                javax.swing.ImageIcon icone = new javax.swing.ImageIcon(iconeURL);

                this.setIconImage(icone.getImage());
            } else {
                logger.warning("Arquivo 'icone.png' não encontrado em /resources/images/");
            }
        } catch (Exception e) {
            logger.severe("Erro ao carregar o ícone: " + e.getMessage());
        }

        MusicPlayerService.getInstance();

        this.setResizable(true);
        this.setPreferredSize(new java.awt.Dimension(800, 600));
        // centraliza o janelas no meio 
        this.setLocationRelativeTo(null);

        // criar objetos da janela
        menuPanel = new MenuPanel();
        gamePanel = new GamePanel();
        rankingPanel = new RankingPanel();
        configPanel = new ConfigPanel();
        selecaoPanel = new SelecaoPanel();

        cardsPanel.add(menuPanel, "MENU");
        cardsPanel.add(gamePanel, "GAME");
        cardsPanel.add(rankingPanel, "RANKING");
        cardsPanel.add(configPanel, "CONFIG");
        cardsPanel.add(selecaoPanel, "SELECAO");

        this.pack();

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                // limpeza a conexão!!
                MongoConnection.fechar();
            }
        });
    }

    public GamePanel getGamePanel() {
        return this.gamePanel;
    }

    public void mostrarTela(String nomeTela) {
        // Pega o "gerenciador" de layout do nosso painel
        java.awt.CardLayout cl = (java.awt.CardLayout) cardsPanel.getLayout();

        // Pede ao gerenciador para "mostrar" o card com o nome fornecido
        cl.show(cardsPanel, nomeTela);

        logger.info(() -> "Navegando para a tela: " + nomeTela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        cardsPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        cardsPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(cardsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        //  INÍCIO DA NOSSA LÓGICA DE CONEXÃO
        try {
            logger.info("Iniciando aplicação. Tentando conectar ao MongoDB Atlas...");

            String conn = "mongodb+srv://appUser:breno123@cluster0.pyhhwz9.mongodb.net/?appName=Cluster0";

            String dbName = "jogodaforca";

            MongoConnection.conectar(conn, dbName);

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(null, """
                                                            N\u00e3o foi poss\u00edvel conectar ao ranking online.
                                                            Verifique sua conex\u00e3o com a internet.
                                                            O modo online estar\u00e1 desabilitado.""",
                    "Erro de Conexão",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        }

        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    public void setModoTela(int modo) {

        dispose();
        switch (modo) {
            case 1: // Sem Borda
                setUndecorated(true);
                setExtendedState(java.awt.Frame.NORMAL);
                setSize(1280, 720);
                break;

            case 2: // Tela Cheia
                setUndecorated(true);
                setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
                break;

            case 0:
            default:
                setUndecorated(false);
                setExtendedState(java.awt.Frame.NORMAL);
                setSize(new java.awt.Dimension(800, 600));
                break;
        }

        setLocationRelativeTo(null);
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardsPanel;
    // End of variables declaration//GEN-END:variables
}
