/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.breno.jogodaforca.view;

import br.com.breno.jogodaforca.dao.MongoConnection;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author breno
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());


    public MainFrame() {
        initComponents();

        this.setResizable(true);
        this.setPreferredSize(new java.awt.Dimension(800, 600));
        // centraliza o janelas no meio 
        this.setLocationRelativeTo(null); 
        
        // criar objetos da janela
        MenuPanel menu = new MenuPanel();
        GamePanel game = new GamePanel();
        RankingPanel rank = new RankingPanel();
        ConfigPanel config = new ConfigPanel();


        cardsPanel.add(menu, "MENU");
        cardsPanel.add(game, "GAME");
        cardsPanel.add(rank, "RANKING");
        cardsPanel.add(config, "CONFIG");
        
        this.pack(); // 1. "Empacota" a janela no tamanho preferido (800x600)

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                // limpeza a conexão!!
                MongoConnection.fechar();
            }
        });
    }
    
    public void mostrarTela(String nomeTela) {
        // Pega o "gerenciador" de layout do nosso painel
        java.awt.CardLayout cl = (java.awt.CardLayout) cardsPanel.getLayout();
        
        // Pede ao gerenciador para "mostrar" o card com o nome fornecido
        cl.show(cardsPanel, nomeTela);
        
        logger.info(() -> "Navegando para a tela: " + nomeTela);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        cardsPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        cardsPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(cardsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        try {
            javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //  --- INÍCIO DA NOSSA LÓGICA DE CONEXÃO ---
        try {
            logger.info("Iniciando aplicação. Tentando conectar ao MongoDB Atlas...");

            String conn = "mongodb+srv://appUser:breno123@cluster0.pyhhwz9.mongodb.net/?appName=Cluster0";

            String dbName = "jogodaforca";

            MongoConnection.conectar(conn, dbName);

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(null, """
                                                            N\u00e3o foi poss\u00edvel conectar ao ranking online.
                                                            Verifique sua conex\u00e3o com a internet.
                                                            O modo online estar\u00e1 desabilitado.""",
                    "Erro de Conexão",
                    javax.swing.JOptionPane.ERROR_MESSAGE);

        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardsPanel;
    // End of variables declaration//GEN-END:variables
}
