/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.breno.jogodaforca.view;
import java.awt.Graphics;



/**
 *
 * @author breno
 */
public class MenuPanel extends javax.swing.JPanel {

    private java.awt.Image imagemDeFundo;
    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnIniciar = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        btnConfiguracoes = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setOpaque(false);
        java.awt.GridBagLayout layout1 = new java.awt.GridBagLayout();
        layout1.columnWidths = new int[] {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0};
        layout1.rowHeights = new int[] {0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0};
        setLayout(layout1);

        btnIniciar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnIniciar.setText("Iniciar Jogo");
        btnIniciar.setBorderPainted(false);
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        add(btnIniciar, gridBagConstraints);

        btnRanking.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRanking.setText("Ver Ranking");
        btnRanking.setBorderPainted(false);
        btnRanking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 40;
        add(btnRanking, gridBagConstraints);

        btnConfiguracoes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConfiguracoes.setText("Configurações");
        btnConfiguracoes.setBorderPainted(false);
        btnConfiguracoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracoesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 56;
        add(btnConfiguracoes, gridBagConstraints);

        btnSair.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorderPainted(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 72;
        add(btnSair, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        // 1. Carrega a imagem (só na primeira vez)
        if (imagemDeFundo == null) {
            try {
                // (Use o nome EXATO do seu arquivo! Ex: "/images/fundo_menu.jpg")
                java.net.URL resource = getClass().getResource("/images/fundo_menu.png");
                if (resource != null) {
                    this.imagemDeFundo = new javax.swing.ImageIcon(resource).getImage();
                }
            } catch (Exception e) {
                System.err.println("Erro ao carregar imagem de fundo: " + e.getMessage());
            }
        }
        
        // 2. "Pinta" a imagem de fundo PRIMEIRO, esticada
        if (imagemDeFundo != null) {
            // Desenha a imagem, esticando-a para caber (getWidth, getHeight)
            g.drawImage(imagemDeFundo, 0, 0, this.getWidth(), this.getHeight(), this);
        } else {
            // Se a imagem falhar, pinta o fundo cinza padrão
            super.paintComponent(g); 
        }

        // 3. Pinta os filhos (botões, labels) DEPOIS (por cima da imagem)
        // Esta linha é MUITO IMPORTANTE!
        super.paintComponent(g);
    }
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracoesActionPerformed
        MainFrame framePai = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        framePai.mostrarTela("CONFIG");

        framePai.setPreferredSize(new java.awt.Dimension(800, 600));
        framePai.setSize(new java.awt.Dimension(800, 600));
        framePai.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnConfiguracoesActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        MainFrame framePai = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        framePai.mostrarTela("RANKING");

        framePai.setPreferredSize(new java.awt.Dimension(800, 600));
        framePai.setSize(new java.awt.Dimension(800, 600));
        framePai.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        MainFrame framePai = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        framePai.mostrarTela("GAME");

        framePai.setPreferredSize(new java.awt.Dimension(1250, 800));
        framePai.setSize(new java.awt.Dimension(1250, 800));
        framePai.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguracoes;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnSair;
    // End of variables declaration//GEN-END:variables

}