/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.breno.jogodaforca.view;

import br.com.breno.jogodaforca.dao.RemoteRankingDAO;
import br.com.breno.jogodaforca.view.MainFrame;
import java.awt.event.ComponentEvent;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author breno
 */
    public class RankingPanel extends javax.swing.JPanel implements java.awt.event.ComponentListener {

    private final RemoteRankingDAO rankingDAO;
    
    public RankingPanel() {
        initComponents();
        
        this.rankingDAO = new RemoteRankingDAO();
        
        this.addComponentListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRanking = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 0));
        setForeground(new java.awt.Color(0, 51, 0));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 12, 0};
        layout.rowHeights = new int[] {0, 14, 0, 14, 0, 14, 0, 14, 0};
        setLayout(layout);

        tblRanking.setForeground(new java.awt.Color(0, 51, 0));
        tblRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Jogador", "Pontuação", "Palavras Vencidas", "Dicas Usadas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRanking);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 5;
        add(jScrollPane1, gridBagConstraints);

        btnVoltar.setText("Voltar ao Menu");
        btnVoltar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnVoltar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnVoltar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(btnVoltar, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Top 25 Ranking Dos Melhores");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void carregarRanking(){
        javax.swing.table.DefaultTableModel model;
        model = (javax.swing.table.DefaultTableModel) tblRanking.getModel();
        
        model.setRowCount(0);
        
        try {
            List<br.com.breno.jogodaforca.model.Partida> top10 = rankingDAO.top25();
            
            int posicao = 1;
            
            for (br.com.breno.jogodaforca.model.Partida p : top10) {
                model.addRow(new Object[]{
                    posicao,
                    p.getJogadorNome(),
                    p.getPontuacao(),
                    p.getPalavrasVencidas(),
                    p.getDicasUsadas()
                
                });
                posicao++;
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,
                    "Não foi possível carregar o ranking online.\nVerifique sua conexão.",
                    "Erro de Conexão",
                    JOptionPane.ERROR_MESSAGE);
        }
    
    }
        
    
    
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MainFrame framePai = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        framePai.mostrarTela("MENU");
        
        framePai.pack();
        framePai.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRanking;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentResized(ComponentEvent e) {
    }

    @Override
    public void componentMoved(ComponentEvent e) {
    }

    @Override
    public void componentShown(ComponentEvent e) {
        carregarRanking();
    }

    @Override
    public void componentHidden(ComponentEvent e) {
    }
}
