/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.breno.jogodaforca.view;

import br.com.breno.jogodaforca.dao.PalavraDAO;
import br.com.breno.jogodaforca.service.GameService;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author breno
 */
public class SelecaoPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelecaoPanel
     */
    
    private PalavraDAO palavraDAO;
    private MainFrame mainFrame;
    
    public SelecaoPanel() {
        initComponents();
        
        this.palavraDAO = new PalavraDAO();
        
        agruparBotoesDificuldade();
        carregarCategorias();
        
        btnJogar.addActionListener(e -> iniciarJogo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitulo = new javax.swing.JLabel();
        panelDificuldade = new javax.swing.JPanel();
        radioFacil = new javax.swing.JRadioButton();
        radioMedio = new javax.swing.JRadioButton();
        radioDificil = new javax.swing.JRadioButton();
        panelCategoria = new javax.swing.JPanel();
        comboCategoria = new javax.swing.JComboBox<>();
        panelBotoes = new javax.swing.JPanel();
        btnVoltarSelecao = new javax.swing.JButton();
        btnJogar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 0));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Configurar Jogo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(lblTitulo, gridBagConstraints);

        panelDificuldade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dificuldade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelDificuldade.setForeground(new java.awt.Color(255, 255, 255));
        panelDificuldade.setOpaque(false);
        panelDificuldade.setRequestFocusEnabled(false);
        panelDificuldade.setLayout(new java.awt.GridLayout(1, 3));

        radioFacil.setForeground(new java.awt.Color(255, 255, 255));
        radioFacil.setText("Fácil (8 erros)");
        panelDificuldade.add(radioFacil);

        radioMedio.setForeground(new java.awt.Color(255, 255, 255));
        radioMedio.setText("Médio (6 erros)");
        panelDificuldade.add(radioMedio);

        radioDificil.setForeground(new java.awt.Color(255, 255, 255));
        radioDificil.setText("Difícil (4 erros)");
        panelDificuldade.add(radioDificil);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(panelDificuldade, gridBagConstraints);

        panelCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelCategoria.setForeground(new java.awt.Color(255, 255, 255));
        panelCategoria.setOpaque(false);
        panelCategoria.setPreferredSize(new java.awt.Dimension(315, 70));
        panelCategoria.setLayout(new java.awt.BorderLayout());

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelCategoria.add(comboCategoria, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        add(panelCategoria, gridBagConstraints);

        panelBotoes.setOpaque(false);
        panelBotoes.setPreferredSize(new java.awt.Dimension(315, 35));
        panelBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnVoltarSelecao.setText("Voltar ao Menu");
        btnVoltarSelecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarSelecaoActionPerformed(evt);
            }
        });
        panelBotoes.add(btnVoltarSelecao);

        btnJogar.setText("INICIAR JOGO");
        panelBotoes.add(btnJogar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        add(panelBotoes, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarSelecaoActionPerformed
            MainFrame framePai = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            framePai.mostrarTela("MENU");
            
            framePai.pack();
            framePai.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVoltarSelecaoActionPerformed
    
    private void agruparBotoesDificuldade(){
        ButtonGroup groupDificuldade = new ButtonGroup();
        groupDificuldade.add(radioFacil);
        groupDificuldade.add(radioMedio);
        groupDificuldade.add(radioDificil);
        
        radioMedio.setSelected(true);
    }

    private void carregarCategorias(){
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) comboCategoria.getModel();
        model.removeAllElements();
        model.addElement("TODAS"); 
        
        try {
            for (String categoria : palavraDAO.getCategorias()) {
                model.addElement(categoria);
            }
        } catch (Exception e) {
            model.addElement("ERRO AO CARREGAR");
        }
    }
    
    private void iniciarJogo(){
        //pegar a dificuldade
        GameService.Dificuldade dificuldade = GameService.Dificuldade.MEDIO;
        if (radioFacil.isSelected()) {
            dificuldade = GameService.Dificuldade.FACIL;
        } else if (radioDificil.isSelected()) {
            dificuldade = GameService.Dificuldade.DIFICIL;
        }
        
        //pegar a categoria
        String categoria = (String) comboCategoria.getSelectedItem();
        
        //pegar a janela princial
        if (mainFrame == null){
            mainFrame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        }
        
        //pegar o painel do jogo
        GamePanel painelJogo = mainFrame.getGamePanel();
        
        //mandar a configuraçao para o gamepanel
        painelJogo.prepararNovoJogo(categoria, dificuldade);
        
        //navegar opra o jogo
        mainFrame.mostrarTela("GAME");
        mainFrame.setPreferredSize(new java.awt.Dimension(1250, 800));
        mainFrame.setSize(new java.awt.Dimension(1250, 800));
        mainFrame.setLocationRelativeTo(null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnVoltarSelecao;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelCategoria;
    private javax.swing.JPanel panelDificuldade;
    private javax.swing.JRadioButton radioDificil;
    private javax.swing.JRadioButton radioFacil;
    private javax.swing.JRadioButton radioMedio;
    // End of variables declaration//GEN-END:variables
}
